workflows:
  build_ios:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      flutter: 3.10.5
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - myprodis
        certificates:
          - mycert
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" # <-- Put the name of your workspace here.
        XCODE_SCHEME: "Runner" # <-- Put the name of your scheme here.
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: pwd
        script: |
          pwd
      - name: ls
        script: |
          ls
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build .ipa
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - ntminhdn@gmail.com
        notify:
          success: true
          failure: true
  
  build_android:
    name: Build Android
    environment:
      flutter: 3.10.5
      android_signing:
        - mykey
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build AAB with Flutter
        script: | 
          flutter build appbundle --release
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - ntminhdn@gmail.com
        notify:
          success: true
          failure: true
          