workflows:
  build_ios:
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'build/stg/*'
          include: true
          source: true 
    name: Build iOS
    scripts:
      - name: Print
        script: | 
          echo "Hello, world!"
  
  build_android:
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'build/stg/*'
          include: true
          source: false 
    name: Build Android
    scripts:
      - name: Print
        script: | 
          echo "Hello, world!"